version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - asset-management-network


  app:
    image: asset_management_service_image
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - asset-management-network

volumes:
  postgres_data:

networks:
  asset-management-network:
    driver: bridge